import React from "react";
import Head from "next/head";
import Faq from "../../modules/contact/faq";

export default function index() {
	return (
		<div>
			<Head>
				<title>Contact Us | Green Light Mentorship</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<Faq />
		</div>
	);
}
