import React from "react";
import Head from "next/head";
import Layout from "../../common/layouts/layout";
import Navbar from "../../common/components/navbar";
import Footer from "../../common/components/footer";
import Header from "../../modules/events/header";
import EventSection from "../../modules/events/eventSection";

export default function index() {
	return (
		<div>
			<Head>
				<title>Events | Green Light Mentorship</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<Header />
			<EventSection />
		</div>
	);
}

index.getLayout = function getLayout(page) {
	return (
		<Layout>
			<Navbar />
			{page}
			<Footer />
		</Layout>
	);
};
