import React from "react";
import Head from "next/head";
import Layout from "../../common/layouts/layout";
import Navbar from "../../common/components/navbar";
import Header from "../../modules/events/header";
import EventSection from "../../modules/events/eventSection";
import MobileNav from "../../common/components/mobileNav";
import MobNavLogo from "../../common/components/mobNavlogo";
import { useState } from 'react'

export default function index() {

	const [open, setOpen] = useState(false);

	return (
		<div>
			<Head>
				<title>Events | Green Light Mentorship</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<MobileNav open={open} setOpen={setOpen} />
			<MobNavLogo open={open} setOpen={setOpen} />
			<Header />
			<EventSection />
		</div>
	);
}

index.getLayout = function getLayout(page) {
	return (
		<Layout>
			<Navbar />
			{page}
			{/*<Footer />*/}
		</Layout>
	);
};
