import React from "react";
import Head from "next/head";
import Layout from "../../common/layouts/layout";
import Navbar from "../../common/components/navbar";
import Summary from "../../modules/about/summary";
import Featured from "../../modules/about/featured";
import Team from "../../modules/about/team";

export default function index() {
	return (
		<div>
			<Head>
				<title>About Us | Green Light Mentorship</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Summary />
			<Featured />
			<Team />
		</div>
	);
}

index.getLayout = function getLayout(page) {
	return (
		<Layout>
			<Navbar />
			{page}
			{/*<Footer />*/}
		</Layout>
	);
};
