import React from "react";
import Head from "next/head";
import Layout from "../../common/layouts/layout";
import Navbar from "../../common/components/navbar";
import Summary from "../../modules/about/summary";
import Featured from "../../modules/about/featured";
import Team from "../../modules/about/team";
import MobileNav from "../../common/components/mobileNav";
import MobNavLogo from "../../common/components/mobNavlogo";
import { useState } from 'react'

export default function index() {

	const [open, setOpen] = useState(false);

	return (
		<div>
			<Head>
				<title>About Us | Green Light Mentorship</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<MobileNav open={open} setOpen={setOpen} />
			<MobNavLogo open={open} setOpen={setOpen} />
			<Summary />
			<Featured />
			<Team />
		</div>
	);
}

index.getLayout = function getLayout(page) {
	return (
		<Layout>
			<Navbar />
			{page}
			{/*<Footer />*/}
		</Layout>
	);
};
