import React from "react";
import Head from "next/head";
//import { defaultTemplate } from "../../common/layouts/templates";
import Layout from "../../common/layouts/layout";
import Navbar from "../../common/components/navbar";
import HeroBanner from "../../modules/home/heroBanner";
import Testimonies from "../../modules/home/testimonies";
import Join from "../../modules/home/join";
import Impacts from "../../modules/home/impacts";
import Socials from "../../modules/home/socials";
import styles from "../../styles/Home.module.css";
import MobileNav from "../../common/components/mobileNav";
import Burger from "../../common/components/burger";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Home | Green Light Mentorship</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<HeroBanner />
			<Testimonies />
			<Join />
			<Impacts />
			<Socials />
			<MobileNav />
			<Burger />
		</div>
	);
}

Home.getLayout = function getLayout(page) {
	return (
		<Layout>
			<Navbar />
			{page}
			{/*<Footer />*/}
		</Layout>
	);
};